# Generated by Django 4.0.3 on 2022-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleKorhrv',
            fields=[
                ('book', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('content', models.TextField()),
                ('fake_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bible_korHRV',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='biblekorhrv',
            constraint=models.UniqueConstraint(fields=('book', 'chapter', 'verse'), name='unique'),
        ),
    ]
