# Generated by Django 4.0.3 on 2022-03-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biblekorhrv',
            table='biblekorHRV',
        ),
    ]
