# Generated by Django 4.0.3 on 2022-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_biblekorhrv_book_alter_biblekorhrv_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblekorhrv',
            name='book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='biblekorhrv',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='biblekorhrv',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='biblekorhrv',
            name='verse',
            field=models.IntegerField(),
        ),
    ]
