# Generated by Django 4.0.3 on 2022-03-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_alter_biblekorhrv_book_alter_biblekorhrv_chapter_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biblekorhrv',
            table='bible_korHRV',
        ),
    ]
